config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  resources :makers
  get 'simple_pages/index'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  root 'simple_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/maker.rb
class Maker < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :makers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/makers_controller.rb
class MakersController < ApplicationController
  before_action :set_maker, only: [:show, :edit, :update, :destroy]

  # GET /makers
  # GET /makers.json
  def index
    @makers = Maker.all
  end

  # GET /makers/1
  # GET /makers/1.json
  def show
  end

  # GET /makers/new
  def new
    @maker = Maker.new
  end

  # GET /makers/1/edit
  def edit
  end

  # POST /makers
  # POST /makers.json
  def create
    @maker = Maker.new(maker_params)

    respond_to do |format|
      if @maker.save
        format.html { redirect_to @maker, notice: 'Maker was successfully created.' }
        format.json { render :show, status: :created, location: @maker }
      else
        format.html { render :new }
        format.json { render json: @maker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /makers/1
  # PATCH/PUT /makers/1.json
  def update
    respond_to do |format|
      if @maker.update(maker_params)
        format.html { redirect_to @maker, notice: 'Maker was successfully updated.' }
        format.json { render :show, status: :ok, location: @maker }
      else
        format.html { render :edit }
        format.json { render json: @maker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makers/1
  # DELETE /makers/1.json
  def destroy
    @maker.destroy
    respond_to do |format|
      format.html { redirect_to makers_url, notice: 'Maker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maker
      @maker = Maker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maker_params
      params.require(:maker).permit(:title, :description, :image_url, :user_id)
    end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user_makers = @user.makers
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        #format.html { redirect_to "/users/new", notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artapp</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top eupopup eupopup-bottomright" role="navigation" id="navigacion">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse"
          data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="Home navbar-brand" id="bberl">
            <!--a href="#">BikeBerlin</a-->
            <%=link_to "WaseemNawaz", root_path, class: "home" %>
          </div> 
        </div> 
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", simple_pages_about_path %></li>
            <li><%= link_to "Contact", simple_pages_contact_path %></li>
            <li class="logina">
              <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                <% else %>
                <%= link_to('Login', new_user_session_path) %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav> <!-- end navbar-->
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<%= yield %>

  <footer>
     &copy; <%= Date.today %> The Art App
  </footer>

  </body>
</html>

app/views/makers/_form.html.erb
<%= form_with(model: maker, local: true) do |form| %>
  <% if maker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(maker.errors.count, "error") %> prohibited this maker from being saved:</h2>

      <ul>
      <% maker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/makers/edit.html.erb
<h1>Editing Maker</h1>

<%= render 'form', maker: @maker %>

<%= link_to 'Show', @maker %> |
<%= link_to 'Back', makers_path %>

app/views/makers/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid anchor">
  <div class="new">
    <h1>The makers</h1>
  </div>
  
  <div class="row" id="productos">
    <% @makers.each do |maker| %>
      <div class="col-md-4">
      <h1><%= link_to maker.title, maker %></h1>
      <p><%= maker.description %></p>
      <p><%= link_to maker.user.first_name, user_path(maker.user) %></p>
      <p><%= link_to maker.user.first_name, maker %></p>
      <p><%= link_to(image_tag(maker.image_url, height:'500',width:'400', class: "img-responsive"), maker) %></p>
      <p><%= link_to 'Show', maker %></p>
      <p><%= link_to 'Edit', edit_maker_path(maker) %></p>
      <p><%= link_to 'Destroy', maker, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    </div><!-- /col -->
    <% end %> 
  </div>
</div>

<h1>Makers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @makers.each do |maker| %>
      <tr>
        <td><%= maker.title %></td>
        <td><%= maker.description %></td>
        <td><%= maker.image_url %></td>
        <td><%= maker.user.first_name %></td>
        <td><%= link_to 'Show', maker %></td>
        <td><%= link_to 'Edit', edit_maker_path(maker) %></td>
        <td><%= link_to 'Destroy', maker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Maker', new_maker_path %>

app/views/makers/new.html.erb
<h1>New Maker</h1>

<%= render 'form', maker: @maker %>

<%= link_to 'Back', makers_path %>

app/views/makers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @maker.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @maker.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= image_tag(@maker.image_url, class: "img-zoom img-responsive bigshowpic") %>
</p>

<p>
  <strong>User:</strong>
  <%= @maker.user_id %>
</p>

<%= link_to 'Edit', edit_maker_path(@maker) %> |
<%= link_to 'Back', makers_path %>

app/views/simple_pages/about.html.erb
<h1>SimplePages#about</h1>
<p>Find me in app/views/simple_pages/about.html.erb</p>

app/views/simple_pages/contact.html.erb
<h1>SimplePages#contact</h1>
<p>Find me in app/views/simple_pages/contact.html.erb</p>

app/views/simple_pages/index.html.erb
<h1>Welcome to the Art App website</h1>
<h2>Your source for Art anywhere</h2>

<%= image_tag("https://cryptic-journey-81193.herokuapp.com/assets/IMG_0694-81f5affadf7b138e1562079512da57c7d59e6aa3e770b5f02670cbf11c126eda.jpg", class: "img-responsive") %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Your id is:</strong>
  <%= @user.id %>
  <strong>Use it whenever you create a new maker or project.</strong>
</p>

<%#= @user.makers %>

<% @user_makers.each do |maker| %>
<p><%= link_to image_tag(maker.image_url, height:'500',width:'400', class: "img-responsive"), maker_path(maker) %></p>
	<p><%= link_to 'Edit', edit_maker_path(maker) %></p>
<% end %>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'New Maker', new_maker_path %>